Update GraalVM to Version 21.0.0
ScoopInstaller/Java pull request #245
Opened 2021-01-22 23:44 UTC by maximumultraist

Version 21.0.0 is out. Update accordingly.

2021-02-26 08:28 UTC, qiyuey approved these changes

2021-02-26 08:45 UTC, se35710 requested changes
Need to update all Graal manifests as described in issue #246

2021-04-01 08:06 UTC, pratikpc commented
I added a PR with GraalVM's version and checkver updated for graalvm8, graalvm11 and graalvm to automate future updates.

Also since GraalVM has released a new version recently, could you [check my PR](https://github.com/ScoopInstaller/Java/pull/255) and share if you have any recommendations @maximumultraist?

2021-04-01 09:41 UTC, se35710 commented
Lets go with #255 instead

2021-04-01 09:41 UTC, closed without merging