ojdkbuild11: add support for old version
ScoopInstaller/Java pull request #392
Opened 2022-05-19 15:19 UTC by chaerun

**Installation logs:**

scoop install ojdkbuild11@11.0.8.10-1
WARN  Given version (11.0.8.10-1) does not match manifest (11.0.15.9-1)
WARN  Attempting to generate manifest for 'ojdkbuild11' (11.0.8.10-1)
Autoupdating ojdkbuild11
Searching hash for java-11-openjdk-11.0.8.10-1.windows.ojdkbuild.x86_64.zip in https://github.com/ojdkbuild/ojdkbuild/releases/download/java-11-openjdk-11.0.8.10-1/java-11-openjdk-11.0.8.10-1.windows.ojdkbuild.x86_64.zip.sha256
Found: 257c50ccb0302483efe71eceb1414eb30d576595d59ec4aa3cbc408217513294 using Extract Mode
Writing updated ojdkbuild11 manifest
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'ojdkbuild11' (11.0.8.10-1) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: b82a05|OK  |   3.1MiB/s|D:/scoop/cache/ojdkbuild11#11.0.8.10-1#https_github.com_ojdkbuild_ojdkbuild_releases_download_java-11-openjdk-11.0.8.10-1_java-11-openjdk-11.0.8.10-1.windows.ojdkbuild.x86_64.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of java-11-openjdk-11.0.8.10-1.windows.ojdkbuild.x86_64.zip ... ok.
Extracting java-11-openjdk-11.0.8.10-1.windows.ojdkbuild.x86_64.zip ... done.
Linking D:\scoop\apps\ojdkbuild11\current => D:\scoop\apps\ojdkbuild11\11.0.8.10-1
'ojdkbuild11' (11.0.8.10-1) was installed successfully!

2022-06-11 09:24 UTC, se35710 requested changes
Thank you! Unsure why `$version` and the other "normal" [version variables](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#version-variables) were not used before.

Please update with the proposed changes, and if possible the other ojdkbuild manifests with the same change.

Do note that the [ojdkbuild is discontinued](https://github.com/ojdkbuild/ojdkbuild#project-is-discontinued-see-official-openjdk-organization-on-github-here-httpsgithubcomopenjdk).

2022-06-11 09:24 UTC, se35710 commented on bucket/ojdkbuild11.json
> +                "extract_dir": "java-11-openjdk-$version.windows.ojdkbuild.x86_64"
```suggestion
                "url": "https://github.com/ojdkbuild/ojdkbuild/releases/download/java-$majorVersion-openjdk-$version/java-$majorVersion-openjdk-$version.windows.ojdkbuild.x86_64.zip",
                "extract_dir": "java-$majorVersion-openjdk-$version.windows.ojdkbuild.x86_64"
```

2022-06-13 01:47 UTC, chaerun commented
> Thank you! Unsure why `$version` and the other "normal" [version variables](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#version-variables) were not used before.

I found the answer. Since Jul 19, 2019, the download URL path changed from `download/$version/` to `download/java-$majorVersion-openjdk-$version/`. That's the reason the `autoupdate.url` use `captured variables`.

> 
> Please update with the proposed changes, and if possible the other ojdkbuild manifests with the same change.
> 
> Do note that [ojdkbuild is discontinued](https://github.com/ojdkbuild/ojdkbuild#project-is-discontinued-see-official-openjdk-organization-on-github-here-httpsgithubcomopenjdk).

The `captured variables` doesn't with `@<version>`. I already report this bug here: https://github.com/ScoopInstaller/Scoop/issues/4985

2022-09-05 08:00 UTC, se35710 approved these changes

2022-09-05 08:01 UTC, merged